//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionSystem {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisionSystem.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddCamera {
            get {
                return ResourceManager.GetString("AddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Password Changed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Adminpwchange {
            get {
                return ResourceManager.GetString("Adminpwchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Delete Image :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AutoDeleteImage {
            get {
                return ResourceManager.GetString("AutoDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Camconn {
            get {
                return ResourceManager.GetString("Camconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Disconnecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string camconndis {
            get {
                return ResourceManager.GetString("camconndis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Connect Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CamConnerr {
            get {
                return ResourceManager.GetString("CamConnerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Count :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CameraCount {
            get {
                return ResourceManager.GetString("CameraCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string changePW {
            get {
                return ResourceManager.GetString("changePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to change the password?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string changePWmsg {
            get {
                return ResourceManager.GetString("changePWmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drive status check operation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string chkDrive {
            get {
                return ResourceManager.GetString("chkDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Commconn {
            get {
                return ResourceManager.GetString("Commconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication Disconnecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string commdis {
            get {
                return ResourceManager.GetString("commdis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommunicationSetting {
            get {
                return ResourceManager.GetString("CommunicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication Connect Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string conncommerr {
            get {
                return ResourceManager.GetString("conncommerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Currentpassword {
            get {
                return ResourceManager.GetString("Currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Insert Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Datainserterr {
            get {
                return ResourceManager.GetString("Datainserterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Load Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dataloaderr {
            get {
                return ResourceManager.GetString("dataloaderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data DB Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dataOpen {
            get {
                return ResourceManager.GetString("dataOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Discrepancy)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Discrepancy {
            get {
                return ResourceManager.GetString("Discrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disk capacity Rate :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DiskcapacityRate {
            get {
                return ResourceManager.GetString("DiskcapacityRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the number of cameras..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string entercamcnt {
            get {
                return ResourceManager.GetString("entercamcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Password :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the quantity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enterquantity {
            get {
                return ResourceManager.GetString("enterquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the screen?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FormDel {
            get {
                return ResourceManager.GetString("FormDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Grabcomplete {
            get {
                return ResourceManager.GetString("Grabcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History Data File Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Historyload {
            get {
                return ResourceManager.GetString("Historyload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Save Path :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageSavePath {
            get {
                return ResourceManager.GetString("ImageSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageSetting {
            get {
                return ResourceManager.GetString("ImageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Parameters Save Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string imgparamnotsave {
            get {
                return ResourceManager.GetString("imgparamnotsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Parameters Saved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string imgParamsave {
            get {
                return ResourceManager.GetString("imgParamsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Init Camera Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string initcamerr {
            get {
                return ResourceManager.GetString("initcamerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Initialization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InitControl {
            get {
                return ResourceManager.GetString("InitControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Init Control Error :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string initcontrolerr {
            get {
                return ResourceManager.GetString("initcontrolerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///    Result 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspResult {
            get {
                return ResourceManager.GetString("InspResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IOconn {
            get {
                return ResourceManager.GetString("IOconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IOdisconn {
            get {
                return ResourceManager.GetString("IOdisconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License actived과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LicenseActive {
            get {
                return ResourceManager.GetString("LicenseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License Checking...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Licensecheck {
            get {
                return ResourceManager.GetString("Licensecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License not actived과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Licensenotactive {
            get {
                return ResourceManager.GetString("Licensenotactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadParam {
            get {
                return ResourceManager.GetString("loadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadrecipe {
            get {
                return ResourceManager.GetString("loadrecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot No : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LotNo {
            get {
                return ResourceManager.GetString("LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Match)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Change : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string modelchange {
            get {
                return ResourceManager.GetString("modelchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ModelSetting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ModelSetting {
            get {
                return ResourceManager.GetString("ModelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No cameras are connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoCam {
            get {
                return ResourceManager.GetString("NoCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no images to save.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoMasterImgMsg {
            get {
                return ResourceManager.GetString("NoMasterImgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator Password Changed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string oppwchange {
            get {
                return ResourceManager.GetString("oppwchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Image Save Format :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OriginalImageSaveFormat {
            get {
                return ResourceManager.GetString("OriginalImageSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Image Save :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OriginImgSave {
            get {
                return ResourceManager.GetString("OriginImgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter Load Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string paramload {
            get {
                return ResourceManager.GetString("paramload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter Load Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string paramloaderr {
            get {
                return ResourceManager.GetString("paramloaderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plcconn {
            get {
                return ResourceManager.GetString("plcconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLC Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plcdisconn {
            get {
                return ResourceManager.GetString("plcdisconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing for the program과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PrepareProgram {
            get {
                return ResourceManager.GetString("PrepareProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please proceed with the communication setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string proceedcomm {
            get {
                return ResourceManager.GetString("proceedcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string programclose {
            get {
                return ResourceManager.GetString("programclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to exit the program?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string programexit {
            get {
                return ResourceManager.GetString("programexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string programstart {
            get {
                return ResourceManager.GetString("programstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passwords do not match과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PWnotMatch {
            get {
                return ResourceManager.GetString("PWnotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recipe Load Error : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string recipeloaderr {
            get {
                return ResourceManager.GetString("recipeloaderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reccord과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-enter Password :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReenterPasswrod {
            get {
                return ResourceManager.GetString("ReenterPasswrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result Image Save :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResultImageSave {
            get {
                return ResourceManager.GetString("ResultImageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result Image Save Format :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResultImageSaveFormat {
            get {
                return ResourceManager.GetString("ResultImageSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master image saved successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveCompleteMasterImg {
            get {
                return ResourceManager.GetString("SaveCompleteMasterImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Image Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveImgSet {
            get {
                return ResourceManager.GetString("SaveImgSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the master image?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveMasterImgMsg {
            get {
                return ResourceManager.GetString("SaveMasterImgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorComm {
            get {
                return ResourceManager.GetString("SensorComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnecting Sensor...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorCommDis {
            get {
                return ResourceManager.GetString("SensorCommDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Connected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorConnected {
            get {
                return ResourceManager.GetString("SensorConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Disconnected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorDisconnected {
            get {
                return ResourceManager.GetString("SensorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the sensor IP.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorIPMsg {
            get {
                return ResourceManager.GetString("SensorIPMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the sensor Port.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SensorPortMsg {
            get {
                return ResourceManager.GetString("SensorPortMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the current time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Settime {
            get {
                return ResourceManager.GetString("Settime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Witdh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
